title: Phone Grown - turn an old phone into a smart display
shorttitle: Phone Grown
email: d.verweij@ncl.ac.uk
description: >-
  Do you have an (old) unused smartphone?
  Turn it into a smart display using Google Sheets and some pen and paper,
  by following this easy step-by-step tutorial.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

search_enabled: false
color_scheme: light

footer_content: "A project by <a href='https://openlab.ncl.ac.uk/' target='_blank'>Open Lab</a>, Newcastle University"
back_to_top: true
back_to_top_text: "Back to top"
